name: ci-deployement
on:
  push:
    branches:
      - 'main'
jobs:
  pushing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qualty-backend:latest

  deploying:
    needs: pushing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: appleboy/ssh-action@v1.0.0
      name: Remove qualty_api container
      with:
        host: 193.203.167.80
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: docker rm -f qualty_api
        
    - uses: chaplyk/docker-compose-remote-action@v1.1
      name: Docker compose up Remote Deployment
      with:
        ssh_host: 193.203.167.80
        ssh_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        compose_file: docker-compose.yaml
        pull: true
        force_recreate: true
      