name: ci-building docker image
on:
  push:
    branches:
      - 'main'
jobs:
  pushing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qualty-backend:latest

  deploy:
    needs: pushing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Stack Remote Deployment
      with:
        ssh_host: 193.203.167.80
        ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        docker_compose_down: 'true'
    
    - uses: chaplyk/docker-compose-remote-action@v1.1
      name: Docker compose up Remote Deployment
      with:
        ssh_host: 193.203.167.80
        ssh_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        compose_file: docker-compose.yaml
        pull: true
      